pool:
  vmImage: 'ubuntu-latest'

- task: GetConjurSecret@1
  inputs:
    conjurapplianceurl: 'https://conjurmaster2.northcentralus.cloudapp.azure.com'
    conjuraccount: 'dev'
    conjurusername: 'host/client/node1'
    conjurapikey: $API_KEY
    ignoreSsl: true