pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  name: conjurCert
  displayName: 'Download CA certificate'
  inputs:
    secureFile: 'conjur-dev.pem'

- task: GetConjurSecret@1
  inputs:
    conjurapplianceurl: 'https://conjurmaster2.northcentralus.cloudapp.azure.com'
    conjuraccount: 'dev'
    conjurusername: 'host/client/node1'
    conjurapikey: $(API_KEY)
    ignoreSsl: true

- bash: |
    cat $(conjurCert.secureFilePath) > $(CONJUR_CERT_FILE)
    echo "Secrets retrieved:"
    echo "  DB_UNAME: $(DB_UNAME) > leaked_secrets.txt"
    echo >> leaked_secrets.txt 
    echo "  DB_PWD: $(DB_PWD) >> leaked_secrets.txt"
    cat leaked_secrets.txt
